version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=graphql_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  postgres_data:
###< doctrine/doctrine-bundle ###
